PollsApp/PollsApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# import polls.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PollsApp/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import *
from accounts.api_views import UserPrivateAPIView
import accounts.authetication as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.AdminLoginView.as_view(), name='login'),
    path('logout/', auth_views.AdminLogoutView.as_view(), name='logout'),
  
    path('users/', UserListView.as_view(), name='list-users'),
    path('users/add', CreateAdminUserView.as_view(), name='add-users'),
    path('users/update/<int:pk>', UpdateAdminUserView.as_view(), name='update-users'),
    path('users/delete/<int:pk>', DeleteAdminUserView.as_view(), name='delete-users'),
    path('users/safe-delete/<int:pk>', DisableUserAdminView.as_view(), name='safe-delete-users'),

    path('users/api/users-list/', UserPrivateAPIView.as_view(), name='api-private-list-users')
    
]

PollsApp/polls/urls.py
from django.urls import path
from polls.views import MainDashboardView, ListPollsView, CreatePollView, UpdatePollView, DeletePollView
from polls.api_views import PollPrivateAPIView

app_name = 'polls'

urlpatterns = [
    path('', MainDashboardView.as_view(), name='index'),

    path('polls/', ListPollsView.as_view(), name='list-polls'),
    path('polls/add', CreatePollView.as_view(), name='add-polls'),
    path('polls/update/<int:pk>', UpdatePollView.as_view(), name='update-polls'),
    path('polls/delete/<int:pk>', DeletePollView.as_view(), name='delete-polls'),
    
    path('polls/api/polls-list/', PollPrivateAPIView.as_view(), name='api-private-list-polls'),
    
]

PollsApp/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from core.models import SafeDeleteAbstractClass

# Create your models here.
class User(AbstractUser, SafeDeleteAbstractClass):
    class TypeUsers(models.TextChoices):
        Employee = 'emp'
        Client = 'cli'

    STATUS_FIELD = 'is_active'

    photo = models.ImageField(upload_to="users/photo-profiles/%Y/%m/%d", null=True)
    birthday = models.DateField(null=True)
    type_user = models.CharField(max_length=3, choices=TypeUsers.choices, null=False, default=TypeUsers.Employee)

PollsApp/accounts/forms.py
from django import forms
from django.http import QueryDict
from django.contrib.auth.forms import AuthenticationForm

from core.filters import FilterForm
from accounts.filters import UserFilter
from accounts.models import User

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

    def confirm_login_allowed(self, user):
        super().confirm_login_allowed(user)
        if user.type_user != User.TypeUsers.Employee:
            raise forms.ValidationError('This user is not allowed')

class FilterUserForm(FilterForm):
    OPTIONS = [('', 'Default'),] + User.TypeUsers.choices 
    filter_class = UserFilter

    username = forms.CharField(
        label='Username',
        max_length=50,
        required=False,
        widget= forms.widgets.TextInput(
            attrs={ 'class':'form-control' }
        )
    )
    email = forms.EmailField(
        label='Email',
        required=False,
        widget=forms.widgets.EmailInput(
            attrs={ 'class':'form-control' }
        )
    )
    type_user = forms.ChoiceField(
        label='Type of user',
        choices=OPTIONS,
        required=False,
        widget=forms.widgets.Select(
            attrs={ 'class': 'form-select' }
        )
    )



class UserForm(forms.ModelForm):
    photo = forms.ImageField(
        required=False,
        widget=forms.widgets.FileInput(
            attrs={'class': 'form-control'}
        )
    )

    def save(self):
        if self.instance.pk is None:
            new_password = User.objects.make_random_password(length=10)
            self.instance.set_password(new_password)
            self.instance.save()
            return self.instance

        return super(UserForm, self).save()
    
    class Meta:
        model = User
        fields = ('photo', 'username', 'first_name', 'last_name', 'email', 'is_active')
        widgets = {
            'username': forms.widgets.TextInput(attrs= {'class': 'form-control'}),
            'first_name': forms.widgets.TextInput(attrs= {'class': 'form-control'}),
            'last_name': forms.widgets.TextInput(attrs= {'class': 'form-control'}),
            'email': forms.widgets.EmailInput(attrs= {'class': 'form-control'}),
            'is_active': forms.widgets.CheckboxInput(attrs={'class':'form-check-input ms-0 fs-3'})
        }

PollsApp/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import CreateView, UpdateView, DeleteView, DetailView

from core.filters import FilterListView

from accounts.forms import FilterUserForm, UserForm
from accounts.models import User
from accounts.authetication import AdminLoginRequiredMixin

class UserListView(AdminLoginRequiredMixin, FilterListView):
    '''
    View that show the users registered in page
    '''
    template_name = 'accounts/users/list_users.html'
    context_object_name = 'users'
    paginate_by = 10
    filter_form_class = FilterUserForm

class CreateAdminUserView(AdminLoginRequiredMixin, CreateView):
    '''
    View for create a new user admin
    '''
    template_name = 'accounts/users/add_users.html'
    form_class = UserForm
    success_url = reverse_lazy('accounts:add-users')

    def form_valid(self, form):
        messages.success(self.request, 'User created successfully')
        return super(CreateAdminUserView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Error when create user. Please check the following fields:')
        return super(CreateAdminUserView, self).form_invalid(form)

class UpdateAdminUserView(AdminLoginRequiredMixin, UpdateView):
    '''
    '''
    template_name = 'accounts/users/update_users.html'
    model = User
    form_class = UserForm

    def _handle_photo_on_error(self, form):
        self.object.photo = form.initial.get("photo", None)

    def get_success_url(self):
        return reverse_lazy('accounts:update-users', kwargs={ 'pk': self.kwargs['pk'] })

    def form_valid(self, form):
        messages.success(self.request, 'User updated successfully')
        return super(UpdateAdminUserView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Error when update user. Please check the following fields:')
        self._handle_photo_on_error(form)
        return super(UpdateAdminUserView, self).form_invalid(form)

class DeleteAdminUserView(AdminLoginRequiredMixin, DeleteView):
    '''
    '''
    template_name = "accounts/users/delete_users.html"
    model = User
    context_object_name = 'user'
    success_url = reverse_lazy('accounts:list-users')

    def form_valid(self, form):
        messages.success(self.request, f'User ({self.get_object()}) deleted sucessfully')
        return super().form_valid(form)

class DisableUserAdminView(AdminLoginRequiredMixin, DeleteView):
    '''
    '''
    template_name = "accounts/users/disable_users.html"
    model = User
    context_object_name = 'user'
    success_url = reverse_lazy('accounts:list-users')

    def form_valid(self, form):
        _user: User = self.object
        _user.safe_delete()
        messages.success(self.request, f'User ({self.get_object()}) has been disabled')
        return HttpResponseRedirect(self.get_success_url())
        

PollsApp/templates/accounts/users/add_users.html
{% extends 'base/base-admin.html' %}

{% load static %}
{% load admin_tags %}

{% block 'css-styles' %}
    <link rel="stylesheet" href="{% static 'accounts/css/users.css' %}">
    <link rel="stylesheet" href="{% static 'shared/css/modals.css' %}">
{% endblock  %}

{% block 'title' %} Add Users {% endblock %}

{% block 'content' %}

    {% if messages and form.errors %}
        {% include 'base/components/form-fail-modal.html' %}
    {% elif messages %}        
        {% include 'accounts/users/modals/add-success.html' %}
    {% endif %}

    <section class="p-3">
        <h1>Add User</h1>
        <hr class="hr my-2"/>
    </section>

    <section class="px-3 mb-3">
        <div class="my-4 px-3 d-flex justify-content-center">
            <img src="{% static 'shared/images/avatar-photo-empty.jpg' %}" alt="avatar-photo" id="img-profile-preview" class="">
        </div>
        <form action="{% url 'accounts:add-users' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3 row">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
                    <div class="col-sm-10 {% if field.name == 'is_active' %} form-check form-switch ps-3 {% endif %}">
                        {{ field }}
                        {% for error in field.errors %}
                            <div class="text-danger">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="mt-4 btn btn-primary btn-lg">
                <i class="bi bi-plus-circle-fill me-2"></i>Add User
            </button>
        </form>
    </section>

{% endblock %}

{% block 'js-scripts' %}
    <script>
        imagePreview({ imgSelector:'#img-profile-preview', fileInputSelector:"input[name='photo']" });
    </script>
{% endblock %}

PollsApp/templates/accounts/users/delete_users.html
<div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-body">
            <div class="d-flex">
                <div class="m-3 icon d-flex justify-content-center">
                    <i class="info bi bi-info-circle-fill"></i>
                </div>
                <div class="message-info d-flex align-items-center">
                    <h4>Are you sure to delete the user ({{ user.username }})?</h4>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <form action="{% url 'accounts:delete-users' user.id %}" method="POST">
                {% csrf_token %}
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
            </form>
        </div>
    </div>
</div>

PollsApp/templates/accounts/users/disable_users.html
<div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-body">
            <div class="d-flex">
                <div class="m-3 icon d-flex justify-content-center">
                    <i class="info bi bi-info-circle-fill"></i>
                </div>
                <div class="message-info d-flex align-items-center">
                    <h4>Are you sure to disable the user ({{ user.username }})?</h4>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <form action="{% url 'accounts:safe-delete-users' user.id %}" method="POST">
                {% csrf_token %}
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
            </form>
        </div>
    </div>
</div>

PollsApp/templates/accounts/users/list_users.html
{% extends 'base/base-admin.html' %}

{% load static %}
{% load admin_tags %}

{% block 'css-styles' %}
    <link rel="stylesheet" href="{% static 'accounts/css/users.css' %}">
    <link rel="stylesheet" href="{% static 'shared/css/modals.css' %}">
    <link rel="stylesheet" href="{% static 'shared/css/pagination.css' %}">
{% endblock  %}

{% block 'title' %} Users {% endblock %}

{% block 'content' %}
    
    {% if messages %}
        {% include 'accounts/users/modals/delete-success.html'%}
    {% endif %}

    <div>
        <section class="p-3">
            <div class="d-flex justify-content-between">
                <h1>Users</h1>
                <a href="{% url 'accounts:add-users' %}" role="button" class="btn btn-success fs-4">
                    <i class="me-3 bi bi-database-fill-add"></i>
                    <span>Add User</span>
                </a>
            </div>
            <hr class="hr my-2"/>
        </section>
        
        <section class="mb-4 px-3">
            <div x-data="CollapseFilterSectionComponent">
                <div class="w-100 mb-2">
                    <button class="btn btn-primary btn-lg" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapse-filters" aria-expanded="false" aria-controls="collapse-filters"
                        x-bind="button">
                        <i class="bi bi-funnel me-2"></i>Filters
                    </button>
                </div>
                <div class="collapse" id="collapse-filters" x-bind="filter">
                    <fieldset class="border rounded-3 p-3">
                        <legend class="float-none w-auto px-3">Filters</legend>
                        <form action="{% url 'accounts:list-users' %}" method="GET">
                            <div class="row g-2 mb-3">
                                {% for field in filter_form %}
                                    <div class="col-md-4">
                                        <div class="form-floating">
                                            {{ field }}
                                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="d-flex justify-content-end">
                                <button type="button" id="reset-btn" class="btn btn-outline-secondary me-2" x-init=""
                                    x-on:click="location.href = '{% url 'accounts:list-users' %}'">
                                    <i class="bi bi-arrow-clockwise me-2"></i>Reset
                                </button>
                                <button class="btn btn-outline-secondary" type="submit">
                                    <i class="bi bi-search me-2"></i>Search
                                </button>
                            </div>
                        </form>
                    </fieldset>
                </div>
            </div>
        </section>
    
        <section class="px-3 mb-4">
            <div class="table-responsive sticky-table-header">
                <table class="table">
                    <thead class="table-header-divider">
                      <tr>
                        <th scope="col">Profile Image</th>
                        <th scope="col">Username</th>
                        <th scope="col">Complete Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Date Joined</th>
                        <th scope="col">State</th>
                        <th scope="col">Actions</th>
                      </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for user in users %}
                            <tr>
                                <td class="align-middle">
                                    {% if user.photo %}
                                        <img src="{{user.photo.url}}" class="img-fluid avatar-img" 
                                            alt="{{user.username}}">
                                    {% else %}
                                        <img src="{% static 'shared/images/avatar-photo-empty.jpg' %}" 
                                            class="img-fluid avatar-img" alt="{{user.username}}">
                                    {% endif %}                
                                </td>
                                <td>{{user.username}}</td>
                                <td>{{user.first_name}} {{user.last_name}}</td>
                                <td>{{user.email}}</td>
                                <td>{{user.date_joined}}</td>
                                <td class="fs-5">
                                    {% if user.is_active %}
                                        <span class="badge bg-success">Active account</span>                                    
                                    {% else %}
                                        <span class="badge bg-danger">Disable account</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <div class="d-flex w-100">
                                        <a href="{% url 'accounts:update-users' user.id %}" 
                                            role="button" class="btn btn-outline-success me-3 fs-5">
                                            <i class="bi bi-arrow-bar-up"></i>
                                        </a>
                                        <button class="btn btn-outline-danger me-3 fs-5"
                                            onclick="chargePageModalByURL('{% url 'accounts:delete-users' user.id %}', '#info-modal')">
                                            <i class="bi bi-trash-fill"></i>
                                        </button>
                                        <button type="button"
                                            {% if not user.is_active %}
                                                class="btn btn-outline-secondary me-3 fs-5" disabled 
                                            {% else %} 
                                                class="btn btn-outline-warning me-3 fs-5" 
                                            {% endif %}
                                            onclick="chargePageModalByURL('{% url 'accounts:safe-delete-users' user.id %}', '#info-modal')" >
                                            <i class="bi bi-lock-fill"></i>    
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="7">No users found</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>    
            </div>
        </section>
        
        <section class="d-flex justify-content-end my-2 px-3 pagination-users">
            {% pagination %}
        </section>
    </div>

    <!-- Modal block -->
    <div class="modal fade" id="info-modal" tabindex="-1" aria-labelledby="modal" data-bs-backdrop="static" data-bs-keyboard="false" 
        aria-hidden="true" role="dialog"></div>

{% endblock %}

{% block 'js-scripts' %}
    <script src="{% static 'accounts/js/users.js' %}"></script>
{% endblock %}

PollsApp/templates/accounts/users/update_users.html
{% extends 'base/base-admin.html' %}

{% load static %}

{% block 'css-styles' %}
    <link rel="stylesheet" href="{% static 'accounts/css/users.css' %}">
    <link rel="stylesheet" href="{% static 'shared/css/modals.css' %}">
{% endblock  %}

{% block 'title' %} Update User {% endblock  %}

{% block 'content' %}

    {% if messages and form.errors %}
        {% include 'base/components/form-fail-modal.html' %}
    {% elif messages %}
        {% include 'accounts/users/modals/update-success.html' %}
    {% endif %}

    <section class="p-3">
        <h1>Update User</h1>
        <hr class="hr my-2"/>
    </section>

    <section class="px-3 mb-3">
        <div class="my-4 px-3 d-flex justify-content-center">
            {% if user.photo %}
                <img src="{{ user.photo.url }}" alt="avatar-photo" id="img-profile-preview" class="">
            {% else %}
                <img src="{% static 'shared/images/avatar-photo-empty.jpg' %}" alt="avatar-photo" id="img-profile-preview" class="">
            {% endif %}
        </div>
        <form action="{% url 'accounts:update-users' user.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3 row">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
                    <div class="col-sm-10 {% if field.name == 'is_active' %} form-check form-switch ps-3 {% endif %}">
                        {{ field }}
                        {% for error in field.errors %}
                            <div class="text-danger">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="mt-4 btn btn-primary btn-lg">
                <i class="bi bi-plus-circle-fill me-2"></i>Update User
            </button>
        </form>
    </section>

{% endblock %}

{% block 'js-scripts' %}
    <script>
        imagePreview({ imgSelector:'#img-profile-preview', fileInputSelector:"input[name='photo']" });
    </script>
{% endblock %}