PollsApp/PollsApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# import polls.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PollsApp/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import *
from accounts.api_views import UserPrivateAPIView
import accounts.authetication as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.AdminLoginView.as_view(), name='login'),
    path('logout/', auth_views.AdminLogoutView.as_view(), name='logout'),
  
    path('users/', UserListView.as_view(), name='list-users'),
    path('users/add', CreateAdminUserView.as_view(), name='add-users'),
    path('users/update/<int:pk>', UpdateAdminUserView.as_view(), name='update-users'),
    path('users/delete/<int:pk>', DeleteAdminUserView.as_view(), name='delete-users'),
    path('users/safe-delete/<int:pk>', DisableUserAdminView.as_view(), name='safe-delete-users'),

    path('users/api/users-list/', UserPrivateAPIView.as_view(), name='api-private-list-users')
    
]

PollsApp/polls/urls.py
from django.urls import path
from polls.views import MainDashboardView, ListPollsView, CreatePollView, UpdatePollView, DeletePollView
from polls.api_views import PollPrivateAPIView

app_name = 'polls'

urlpatterns = [
    path('', MainDashboardView.as_view(), name='index'),

    path('polls/', ListPollsView.as_view(), name='list-polls'),
    path('polls/add', CreatePollView.as_view(), name='add-polls'),
    path('polls/update/<int:pk>', UpdatePollView.as_view(), name='update-polls'),
    path('polls/delete/<int:pk>', DeletePollView.as_view(), name='delete-polls'),
    
    path('polls/api/polls-list/', PollPrivateAPIView.as_view(), name='api-private-list-polls'),
    
]

PollsApp/templates/base/layouts/side-navbar.html
{% load static %}

<nav class="navbar d-grid py-3 h-100">
    <div class="header-navbar my-2 px-3">
        <div class="text-center">
            {% if request.user.photo %}
                <img src="{{ request.user.photo.url }}" alt="avatar-imagen">
            {% else %}
                <img src="{% static 'shared/images/avatar-imagen.jpg' %}" alt="avatar-imagen">
            {% endif %}
        </div>
        <div class="d-flex flex-column">
            <span>{{ request.user.username|default:'Username' }}</span>
            <span>
                {% if request.user.is_active %}
                    <span class="badge bg-success">Active</span>
                {% endif %}
            </span>
        </div>
    </div>
    <ul class="navbar-nav w-100" 
        x-data="{
            sectionSelected: $persist('').using(sessionStorage)
        }">
        <li class="nav-item" data-section="home" 
            x-on:click="sectionSelected = $el.dataset.section"
            x-bind:class="sectionSelected == $el.dataset.section && 'active'">
            <a class="nav-link p-4" href="{% url 'polls:index' %}">
                <i class="bi bi-house"></i>
                <span>Home</span>
            </a>
        </li>
        <li class="nav-item" data-section="users"
            x-on:click="sectionSelected = $el.dataset.section"
            x-bind:class="sectionSelected == $el.dataset.section && 'active'">
            <a class="nav-link p-4" href="{% url 'accounts:list-users' %}">
                <i class="bi bi-person-circle"></i>
                <span>Users</span>
            </a>
        </li>
        <li class="nav-item" data-section="polls"
            x-on:click="sectionSelected = $el.dataset.section"
            x-bind:class="sectionSelected == $el.dataset.section && 'active'">
            <a class="nav-link p-4" href="{% url 'polls:list-polls' %}">
                <i class="bi bi-clipboard-check-fill"></i>
                <span>Polls</span>
            </a>
        </li>
        <li class="nav-item" data-section="roles"
            x-on:click="sectionSelected = $el.dataset.section"
            x-bind:class="sectionSelected == $el.dataset.section && 'active'">
            <a class="nav-link p-4" href="#">
                <i class="bi bi-people-fill"></i>
                <span>Roles</span>
            </a>
         </li>
    </ul>
    <div class="footer-navbar">
        Footer
    </div>
</nav>

PollsApp/templates/base/layouts/top-navbar.html
<nav class="navbar">
    <div class="container-fluid">
        <button id='toggle-sidebar' type="button" x-data="ButtonToggleComponent" 
            x-bind="actionSidebarButton">
            <i class="bi bi-list"></i>
        </button>
        <div class="navbar">
            <ul class="nav">
                <li class="nav-item px-2">
                    <a href="{% url 'accounts:logout' %}" class="btn btn-outline-light" rol="button"
                        x-data x-bind="LogoutButton"> Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>