PollsApp/PollsApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# import polls.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PollsApp/polls/urls.py
from django.urls import path
from polls.views import MainDashboardView, ListPollsView, CreatePollView, UpdatePollView, DeletePollView
from polls.api_views import PollPrivateAPIView

app_name = 'polls'

urlpatterns = [
    path('', MainDashboardView.as_view(), name='index'),

    path('polls/', ListPollsView.as_view(), name='list-polls'),
    path('polls/add', CreatePollView.as_view(), name='add-polls'),
    path('polls/update/<int:pk>', UpdatePollView.as_view(), name='update-polls'),
    path('polls/delete/<int:pk>', DeletePollView.as_view(), name='delete-polls'),
    
    path('polls/api/polls-list/', PollPrivateAPIView.as_view(), name='api-private-list-polls'),
    
]

PollsApp/polls/models.py
from typing import List

from django.db import models

from core.models import SafeDeleteModel

# Create your models here.

class Poll(SafeDeleteModel):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(null=True, upload_to='polls/images/%Y/%m/%d')
    date_created = models.DateTimeField(auto_created=True, auto_now=True)

class Question(models.Model):
    class TypeQuestion(models.TextChoices):
        MULTIPLE_OPTIONS = 'multiple-opt'
        UNIQUE_OPTIONS = 'unique-opt'

    sentence = models.CharField(max_length=250, null=False)
    type_question = models.CharField(max_length=20, choices=TypeQuestion.choices, default=TypeQuestion.UNIQUE_OPTIONS)
    poll = models.ForeignKey(Poll, related_name='questions', on_delete=models.CASCADE, null=False)

class Option(models.Model):
    sentence = models.CharField(max_length=250, null=False)
    question = models.ForeignKey(Question, related_name='options', on_delete=models.CASCADE, null=False)

PollsApp/polls/forms.py
from django import forms

from polls.models import *

class PollForm(forms.ModelForm):
    image = forms.ImageField(
        required=False,
        widget=forms.widgets.FileInput(
            attrs={'class': 'form-control'}
        )
    )

    questions_objects = forms.JSONField(
        required=False,
        label='',
        widget= forms.widgets.Textarea(attrs={'hidden': 'hidden'})
    )

    def clean_questions_objects(self):
        questions = self.cleaned_data["questions_objects"]
        questions = list(filter(lambda q: q['sentence'] != '' and q['type_question'] != '', questions))
        for q in questions:
            q['options'] = list(filter(lambda opt: opt['sentence'] != '', q['options']))
        return questions

    def create_poll(self):
        _poll: Poll = super().save()
        questions = self.cleaned_data['questions_objects']

        for question in questions:
            options = question.pop('options')
            _created_question = Question(**question)
            _poll.questions.add(_created_question, bulk=False)

            for opt in options:
                _created_option = Option(**opt)
                _created_question.options.add(_created_option, bulk=False)

        return _poll


    def update_poll(self):
        _poll: Poll = super().save()
        questions = self.cleaned_data['questions_objects']
        
        questions_updated_ids = []
        options_updated_ids = []

        for q in questions:
            options = q.pop('options')
            _question = Question(**q)
            _question.poll = _poll
            _question.save()
            questions_updated_ids.append(_question.id)

            for option in options:
                _opt = Option(**option)
                _opt.question = _question
                _opt.save()
                options_updated_ids.append(_opt.id)

        Option.objects.filter(question__poll=_poll).exclude(id__in=options_updated_ids).delete()
        _poll.questions.exclude(id__in=questions_updated_ids).delete()

        return _poll

    def save(self):
        if self.instance.pk is None:
            return self.create_poll()
        return self.update_poll()

    class Meta:
        model = Poll
        fields = ('image', 'title', 'description', 'questions_objects')
        widgets = {
            'title': forms.widgets.TextInput(attrs= {'class': 'form-control'}),
            'description': forms.widgets.Textarea(attrs={'class': 'form-control'}),
        }

PollsApp/polls/views.py
from django.shortcuts import render

from django.core import serializers
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DeleteView

from polls.forms import PollForm
from polls.models import *
from polls.serializers import QuestionSerializer

from accounts.authetication import AdminLoginRequiredMixin
from accounts.models import User

import json

# Create your views here.
class MainDashboardView(AdminLoginRequiredMixin, TemplateView):
    template_name = 'polls/main/main-page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['polls_count'] = Poll.objects.count()
        context['questions_count'] = Question.objects.count()
        context['users_count'] = User.objects.count()

        print(context)
        return context
    

class ListPollsView(AdminLoginRequiredMixin, ListView):
    template_name = 'polls/polls/list_polls.html'
    context_object_name = 'polls'
    paginate_by = 10

    def get_queryset(self):
        return Poll.objects.all()

class CreatePollView(AdminLoginRequiredMixin, CreateView):
    template_name = 'polls/polls/add_polls.html'
    form_class = PollForm
    success_url = reverse_lazy('polls:add-polls')

    def form_valid(self, form):
        messages.success(self.request, 'Poll created successfully')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Error when create poll. Please check the following fields:')
        return super().form_invalid(form)

class UpdatePollView(AdminLoginRequiredMixin, UpdateView):
    template_name = 'polls/polls/update_polls.html'
    model = Poll
    form_class = PollForm

    def get_success_url(self):
        return reverse_lazy('polls:update-polls', kwargs={ 'pk': self.kwargs['pk'] })

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        _questions = QuestionSerializer(self.get_object().questions.all(), many=True)
        context["questions_serialized"] = _questions.data
        return context

    def form_valid(self, form):
        messages.success(self.request, 'Poll updated successfully')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Error when update poll. Please check the following fields:')
        return super().form_invalid(form)

class DeletePollView(AdminLoginRequiredMixin, DeleteView):
    template_name = 'polls/polls/delete_polls.html'
    model = Poll
    context_object_name = 'poll'
    success_url = reverse_lazy('polls:list-polls')
    
    def form_valid(self, form):
        messages.success(self.request, f"Poll '{self.get_object().title}' has been delete.")
        return super().form_valid(form)

PollsApp/templates/polls/polls/add_polls.html
{% extends 'base/base-admin.html' %}

{% load static %}
{% load admin_tags %}

{% block 'css-styles' %}
    <link rel="stylesheet" href="{% static 'polls/css/polls.css' %}">
    <link rel="stylesheet" href="{% static 'shared/css/modals.css' %}">
{% endblock  %}

{% block 'title' %} Add Poll {% endblock %}

{% block 'content' %}

    {% if messages and form.errors %}
        {% include 'base/components/form-fail-modal.html' %}
    {% elif messages %}        
        {% include 'polls/polls/modals/add-success.html' %}
    {% endif %}

    <section class="p-3">
        <h1>Add Poll</h1>
        <hr class="hr my-2"/>
    </section>

    <section class="px-3 mb-3">

        <!-- Form Component -->
        <div x-data="QuestionOptionComponent">
            <div class="my-4 px-3 d-flex justify-content-center">
                <img src="{% static 'shared/images/avatar-photo-empty.jpg' %}" alt="avatar-photo" id="img-poll-preview" class="">
            </div>
            <form action="{% url 'polls:add-polls' %}" method="post" enctype="multipart/form-data" id="poll-form">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'questions_objects'  %}
                        <div class="mb-3 row">
                            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
                            <div class="col-sm-10 {% if field.name == 'is_active' %} form-check form-switch ps-3 {% endif %}">
                                {{ field }}
                                {% for error in field.errors %}
                                    <div class="text-danger">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% else %}
                        <div class="mb-3 row">
                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}

                <template x-for="(question, question_index) in questions" :key="question_index">
                    <div class="border rounded-3 p-3 mb-3">
                        <div class="mb-3 row">
                            <div class="my-2 d-flex justify-content-between">
                                <h4 x-text="`Question ${question_index+1}`"></h4>
                                <button type="button" class="btn btn-outline-dark" @click="removeQuestion(question_index)" title="Delete Question">
                                    <i class="bi bi-x-lg"></i>
                                </button>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="" class="col-sm-2 col-form-label">Sentence:</label>
                            <div class="col-sm-10">
                                <input type="text" id="" class="form-control" x-model="question.sentence">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="" class="col-sm-2 col-form-label">Type Question:</label>
                            <div class="col-sm-10">
                                <select name="" id="1" class="form-select" x-model="question.type_question">
                                    <option value="" selected disabled>---</option>
                                    <option value="multiple-opt">Multiple choices</option>
                                    <option value="unique-opt">Unique choice</option>
                                </select>
                            </div>
                        </div>
                        <template x-for="(option, index_option) in question.options" :key="index_option">
                            <div class="mb-3 row">
                                <label for="" class="col-sm-2 col-form-label" x-text="`Option ${index_option+1}`"></label>
                                <div class="col-sm-10">
                                    <div class="d-flex">
                                        <input type="text" id="" class="form-control me-2" x-model="option.sentence">
                                        <button type="button" class="btn btn-danger" @click="removeOption(question_index, index_option)" title="Delete Option">
                                            <i class="bi bi-trash-fill"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </template>
                        <div class="mb-3 row">
                            <div class="col d-flex justify-content-end">
                                <button type="button" class="btn btn-primary btn-lg" @click="addEmptyOption(question_index)" title="Add Option">
                                    <i class="bi bi-plus-lg"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </template>
                <div class="mt-3 d-flex justify-content-end">
                    <button type="button" class="btn btn-primary btn-lg" @click="addEmptyQuestion()" title="Add Question">
                        <i class="bi bi-file-earmark-plus me-2"></i> Add Question
                    </button>
                </div>
    
                <button type="button" class="mt-4 btn btn-primary btn-lg" x-bind="buttonAction">
                    <i class="bi bi-plus-circle-fill me-2"></i>Add Poll
                </button>
            </form>
        </div>
        
    </section>

{% endblock %}

{% block 'js-scripts' %}
    <script>
        imagePreview({ imgSelector:'#img-poll-preview', fileInputSelector:"input[name='image']" });
    </script>
    <script src="{% static 'polls/js/polls.js' %}"></script>
{% endblock %}

PollsApp/templates/polls/polls/delete_polls.html
<div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-body">
            <div class="d-flex">
                <div class="m-3 icon d-flex justify-content-center">
                    <i class="info bi bi-info-circle-fill"></i>
                </div>
                <div class="message-info d-flex align-items-center">
                    <h4>Are you sure to delete this poll ({{ poll.title }})?</h4>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <form action="{% url 'polls:delete-polls' poll.id %}" method="POST">
                {% csrf_token %}
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
            </form>
        </div>
    </div>
</div>

PollsApp/templates/polls/polls/list_polls.html
{% extends 'base/base-admin.html' %}

{% load static %}
{% load admin_tags %}

{% block 'css-styles' %}
    <link rel="stylesheet" href="{% static 'polls/css/polls.css' %}">
    <link rel="stylesheet" href="{% static 'shared/css/modals.css' %}">
    <link rel="stylesheet" href="{% static 'shared/css/pagination.css' %}">
{% endblock  %}

{% block 'content' %}

    {% if messages %}
        {% include 'polls/polls/modals/delete-success.html'%}
    {% endif %}

    <div>
        <section class="p-3">
            <div class="d-flex justify-content-between">
                <h1>Polls</h1>
                <a href="{% url 'polls:add-polls' %}" role="button" class="btn btn-success fs-4">
                    <i class="me-3 bi bi-database-fill-add"></i>
                    <span>Add Poll</span>
                </a>
            </div>
            <hr class="hr my-2"/>
        </section>

        <section class="px-3 mb-4">
            <div class="table-responsive sticky-table-header">
                <table class="table">
                    <thead class="table-header-divider">
                      <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Date Created</th>
                        <th scope="col">Actions</th>
                      </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for poll in polls %}
                            <tr>
                                <td class="image-cell">
                                    {% if poll.image %}
                                        <img src="{{ poll.image.url }}" alt="{{poll.title}}" class="img-fluid img-poll ps-2">
                                    {% else %}
                                        <img src="{% static 'shared/images/avatar-photo-empty.jpg' %}" alt="{{poll.title}}" class="img-fluid img-poll ps-2">
                                    {% endif %}                                    
                                </td>
                                <td>{{poll.title}}</td>
                                <td>{{poll.description}}</td>
                                <td>{{poll.date_created}}</td>
                                <td>
                                    <div class="d-flex w-100">
                                        <a href="{% url 'polls:update-polls' poll.id %}" 
                                            role="button" class="btn btn-outline-success me-3 fs-5">
                                            <i class="bi bi-arrow-bar-up"></i>
                                        </a>
                                        <button class="btn btn-outline-danger me-3 fs-5"
                                            onclick="chargePageModalByURL('{% url 'polls:delete-polls' poll.id %}', '#info-modal')">
                                            <i class="bi bi-trash-fill"></i>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5">No polls found</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>    
            </div>
        </section>

        <section class="d-flex justify-content-end my-2 px-3 pagination-users">
            {% pagination %}
        </section>
    </div>

    <!-- Modal block -->
    <div class="modal fade" id="info-modal" tabindex="-1" aria-labelledby="modal" data-bs-backdrop="static" data-bs-keyboard="false" 
        aria-hidden="true" role="dialog"></div>
{% endblock %}

PollsApp/templates/polls/polls/update_polls.html
{% extends 'base/base-admin.html' %}

{% load static %}
{% load admin_tags %}

{% block 'css-styles' %}
    <link rel="stylesheet" href="{% static 'polls/css/polls.css' %}">
    <link rel="stylesheet" href="{% static 'shared/css/modals.css' %}">
{% endblock  %}

{% block 'title' %} Update Poll {% endblock %}

{% block 'content' %}

    {% if messages and form.errors %}
        {% include 'base/components/form-fail-modal.html' %}
    {% elif messages %}        
        {% include 'polls/polls/modals/update-success.html' %}
    {% endif %}

    <section class="p-3">
        <h1>Update Poll</h1>
        <hr class="hr my-2"/>
    </section>

    <section class="px-3 mb-3">

        <!-- Form Component-->
        <div x-data="QuestionOptionComponent">
            <div class="my-4 px-3 d-flex justify-content-center">
                {% if poll.image %}
                    <img src="{{ poll.image.url }}" alt="{{ poll.title }}" id="img-poll-preview">
                {% else %}
                    <img src="{% static 'shared/images/avatar-photo-empty.jpg' %}" alt="avatar-photo" id="img-poll-preview" class="">
                {% endif %}
            </div>
            <form action="{% url 'polls:update-polls' poll.id %}" method="post" enctype="multipart/form-data" id="poll-form">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'questions_objects'  %}
                        <div class="mb-3 row">
                            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
                            <div class="col-sm-10 {% if field.name == 'is_active' %} form-check form-switch ps-3 {% endif %}">
                                {{ field }}
                                {% for error in field.errors %}
                                    <div class="text-danger">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% else %}
                        <div class="mb-3 row">
                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}

                <template x-for="(question, question_index) in questions" :key="question_index">
                    <div class="border rounded-3 p-3 mb-3">
                        <div class="mb-3 row">
                            <div class="my-2 d-flex justify-content-between">
                                <h4 x-text="`Question ${question_index+1}`"></h4>
                                <button type="button" class="btn btn-outline-dark" @click="removeQuestion(question_index)" title="Delete Question">
                                    <i class="bi bi-x-lg"></i>
                                </button>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="" class="col-sm-2 col-form-label">Sentence:</label>
                            <div class="col-sm-10">
                                <input type="text" required class="form-control" x-model="question.sentence">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="" class="col-sm-2 col-form-label">Type Question:</label>
                            <div class="col-sm-10">
                                <select class="form-select" required x-model="question.type_question">
                                    <option value="" selected disabled>---</option>
                                    <option value="multiple-opt">Multiple choices</option>
                                    <option value="unique-opt">Unique choice</option>
                                </select>
                            </div>
                        </div>
                        <template x-for="(option, index_option) in question.options" :key="index_option">
                            <div class="mb-3 row">
                                <label for="" class="col-sm-2 col-form-label" x-text="`Option ${index_option+1}`"></label>
                                <div class="col-sm-10">
                                    <div class="d-flex">
                                        <input type="text" required class="form-control me-2" x-model="option.sentence">
                                        <button type="button" class="btn btn-danger" @click="removeOption(question_index, index_option)" title="Delete Option">
                                            <i class="bi bi-trash-fill"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </template>
                        <div class="mb-3 row">
                            <div class="col d-flex justify-content-end">
                                <button type="button" class="btn btn-primary btn-lg" @click="addEmptyOption(question_index)" title="Add Option">
                                    <i class="bi bi-plus-lg"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </template>
                <div class="mt-3 d-flex justify-content-end">
                    <button type="button" class="btn btn-primary btn-lg" @click="addEmptyQuestion()" title="Add Question">
                        <i class="bi bi-file-earmark-plus me-2"></i> Add Question
                    </button>
                </div>
    
                <button type="submit" class="mt-4 btn btn-primary btn-lg" x-bind="buttonAction">
                    <i class="bi bi-plus-circle-fill me-2"></i>Update
                </button>
            </form>
        </div>

    </section>

{% endblock %}

{% block 'js-scripts' %}
    <script src="{% static 'polls/js/polls.js' %}"></script>
    {{ questions_serialized|json_script:"questions" }}
    <script>
        imagePreview({ imgSelector:'#img-poll-preview', fileInputSelector:"input[name='image']" });
    </script>
{% endblock %}