PollsApp/PollsApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# import polls.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PollsApp/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import *
from accounts.api_views import UserPrivateAPIView
import accounts.authetication as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.AdminLoginView.as_view(), name='login'),
    path('logout/', auth_views.AdminLogoutView.as_view(), name='logout'),
  
    path('users/', UserListView.as_view(), name='list-users'),
    path('users/add', CreateAdminUserView.as_view(), name='add-users'),
    path('users/update/<int:pk>', UpdateAdminUserView.as_view(), name='update-users'),
    path('users/delete/<int:pk>', DeleteAdminUserView.as_view(), name='delete-users'),
    path('users/safe-delete/<int:pk>', DisableUserAdminView.as_view(), name='safe-delete-users'),

    path('users/api/users-list/', UserPrivateAPIView.as_view(), name='api-private-list-users')
    
]

PollsApp/polls/urls.py
from django.urls import path
from polls.views import MainDashboardView, ListPollsView, CreatePollView, UpdatePollView, DeletePollView
from polls.api_views import PollPrivateAPIView

app_name = 'polls'

urlpatterns = [
    path('', MainDashboardView.as_view(), name='index'),

    path('polls/', ListPollsView.as_view(), name='list-polls'),
    path('polls/add', CreatePollView.as_view(), name='add-polls'),
    path('polls/update/<int:pk>', UpdatePollView.as_view(), name='update-polls'),
    path('polls/delete/<int:pk>', DeletePollView.as_view(), name='delete-polls'),
    
    path('polls/api/polls-list/', PollPrivateAPIView.as_view(), name='api-private-list-polls'),
    
]

PollsApp/polls/models.py
from typing import List

from django.db import models

from core.models import SafeDeleteModel

# Create your models here.

class Poll(SafeDeleteModel):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(null=True, upload_to='polls/images/%Y/%m/%d')
    date_created = models.DateTimeField(auto_created=True, auto_now=True)

class Question(models.Model):
    class TypeQuestion(models.TextChoices):
        MULTIPLE_OPTIONS = 'multiple-opt'
        UNIQUE_OPTIONS = 'unique-opt'

    sentence = models.CharField(max_length=250, null=False)
    type_question = models.CharField(max_length=20, choices=TypeQuestion.choices, default=TypeQuestion.UNIQUE_OPTIONS)
    poll = models.ForeignKey(Poll, related_name='questions', on_delete=models.CASCADE, null=False)

class Option(models.Model):
    sentence = models.CharField(max_length=250, null=False)
    question = models.ForeignKey(Question, related_name='options', on_delete=models.CASCADE, null=False)

PollsApp/polls/forms.py
from django import forms

from polls.models import *

class PollForm(forms.ModelForm):
    image = forms.ImageField(
        required=False,
        widget=forms.widgets.FileInput(
            attrs={'class': 'form-control'}
        )
    )

    questions_objects = forms.JSONField(
        required=False,
        label='',
        widget= forms.widgets.Textarea(attrs={'hidden': 'hidden'})
    )

    def clean_questions_objects(self):
        questions = self.cleaned_data["questions_objects"]
        questions = list(filter(lambda q: q['sentence'] != '' and q['type_question'] != '', questions))
        for q in questions:
            q['options'] = list(filter(lambda opt: opt['sentence'] != '', q['options']))
        return questions

    def create_poll(self):
        _poll: Poll = super().save()
        questions = self.cleaned_data['questions_objects']

        for question in questions:
            options = question.pop('options')
            _created_question = Question(**question)
            _poll.questions.add(_created_question, bulk=False)

            for opt in options:
                _created_option = Option(**opt)
                _created_question.options.add(_created_option, bulk=False)

        return _poll


    def update_poll(self):
        _poll: Poll = super().save()
        questions = self.cleaned_data['questions_objects']
        
        questions_updated_ids = []
        options_updated_ids = []

        for q in questions:
            options = q.pop('options')
            _question = Question(**q)
            _question.poll = _poll
            _question.save()
            questions_updated_ids.append(_question.id)

            for option in options:
                _opt = Option(**option)
                _opt.question = _question
                _opt.save()
                options_updated_ids.append(_opt.id)

        Option.objects.filter(question__poll=_poll).exclude(id__in=options_updated_ids).delete()
        _poll.questions.exclude(id__in=questions_updated_ids).delete()

        return _poll

    def save(self):
        if self.instance.pk is None:
            return self.create_poll()
        return self.update_poll()

    class Meta:
        model = Poll
        fields = ('image', 'title', 'description', 'questions_objects')
        widgets = {
            'title': forms.widgets.TextInput(attrs= {'class': 'form-control'}),
            'description': forms.widgets.Textarea(attrs={'class': 'form-control'}),
        }

PollsApp/polls/views.py
from django.shortcuts import render

from django.core import serializers
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DeleteView

from polls.forms import PollForm
from polls.models import *
from polls.serializers import QuestionSerializer

from accounts.authetication import AdminLoginRequiredMixin
from accounts.models import User

import json

# Create your views here.
class MainDashboardView(AdminLoginRequiredMixin, TemplateView):
    template_name = 'polls/main/main-page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['polls_count'] = Poll.objects.count()
        context['questions_count'] = Question.objects.count()
        context['users_count'] = User.objects.count()

        print(context)
        return context
    

class ListPollsView(AdminLoginRequiredMixin, ListView):
    template_name = 'polls/polls/list_polls.html'
    context_object_name = 'polls'
    paginate_by = 10

    def get_queryset(self):
        return Poll.objects.all()

class CreatePollView(AdminLoginRequiredMixin, CreateView):
    template_name = 'polls/polls/add_polls.html'
    form_class = PollForm
    success_url = reverse_lazy('polls:add-polls')

    def form_valid(self, form):
        messages.success(self.request, 'Poll created successfully')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Error when create poll. Please check the following fields:')
        return super().form_invalid(form)

class UpdatePollView(AdminLoginRequiredMixin, UpdateView):
    template_name = 'polls/polls/update_polls.html'
    model = Poll
    form_class = PollForm

    def get_success_url(self):
        return reverse_lazy('polls:update-polls', kwargs={ 'pk': self.kwargs['pk'] })

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        _questions = QuestionSerializer(self.get_object().questions.all(), many=True)
        context["questions_serialized"] = _questions.data
        return context

    def form_valid(self, form):
        messages.success(self.request, 'Poll updated successfully')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Error when update poll. Please check the following fields:')
        return super().form_invalid(form)

class DeletePollView(AdminLoginRequiredMixin, DeleteView):
    template_name = 'polls/polls/delete_polls.html'
    model = Poll
    context_object_name = 'poll'
    success_url = reverse_lazy('polls:list-polls')
    
    def form_valid(self, form):
        messages.success(self.request, f"Poll '{self.get_object().title}' has been delete.")
        return super().form_valid(form)

PollsApp/templates/polls/main/main-page.html
{% extends 'base/base-admin.html' %}

{% load static %}

{% block 'css-styles' %}
    <link rel="stylesheet" href="{% static 'polls/css/main-dashboard.css' %}">
{% endblock %}

{% block 'js-headers-scripts' %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js"></script>
{% endblock  %}

{% block 'content' %}
    <section class="p-3">
        <div class="d-flex justify-content-between">
            <h1>Principal View</h1>
        </div>
        <hr class="hr my-2"/>
    </section>
    <section class="p-3">
        <div class="mb-5">
            <h3>Info</h3>
        </div>

        <div class="row gap-3">
            <div class="col-12 col-lg">
                <div class="card">
                    <div class="icon-card" id="users-icon">
                        <i class="bi bi-people-fill"></i>
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">{{ users_count }} Users</h5>
                      <h6 class="card-subtitle mb-2 text-muted">Registered in this system</h6>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg">
                <div class="card">
                    <div class="icon-card" id="polls-icon">
                        <i class="bi bi-file-earmark-bar-graph"></i>
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">{{ polls_count }} Polls</h5>
                      <h6 class="card-subtitle mb-2 text-muted">Have been created</h6>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg">
                <div class="card">
                    <div class="icon-card" id="question-icon">
                        <i class="bi bi-file-earmark-diff-fill"></i>
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">{{ questions_count }} Questions</h5>
                      <h6 class="card-subtitle mb-2 text-muted">Have been created</h6>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <section class="p-3">
        <div class="mb-5">
            <h3>Charts</h3>
        </div>
        <div class="row" id="charts"> 
            <div class="col-6 col-md">
                <div class="card">
                    <div class="card-body">
                        <div class="chart-wrapper">
                            <canvas id="polls-chart"></canvas>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md">
                <div class="card">
                    <div class="card-body">
                        <div class="chart-wrapper">
                            <canvas id="users-chart"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block 'js-scripts' %}
    <script src="{% static 'polls/js/main-dashboard.js' %}"></script>
    <script>
        buildPollChart(`{% url 'polls:api-private-list-polls' %}`);
        buildUsersChart(`{% url 'accounts:api-private-list-users' %}`);
    </script>
{% endblock %}